#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOMELAB_ENV="/etc/homelab/holiday-house-comparison.env"
LEGACY_CONFIG="$SCRIPT_DIR/deploy.config"
LOCAL_FILE="$SCRIPT_DIR/public/index.html"
AUTH_DIR="$SCRIPT_DIR/deploy_auth"
AUTH_STATE_FILE="$AUTH_DIR/.auth_state"
AUTH_SECRET_PHP="$AUTH_DIR/auth_secret.php"
AUTH_COOKIE_SECONDS=$((30 * 24 * 60 * 60))

# Credentials + SITE_PASSWORD: /etc/homelab/holiday-house-comparison.env (§4) if
# present, else the legacy repo-local deploy.config -- kept only for machines that
# predate this server's onboarding (see compliance/holiday-house-comparison.md §4
# in the infrastructure repo). Prefer the env file; it's what keeps these values
# off server-backup-sync.sh's wholesale /samba/ rsync.
if [ -f "$HOMELAB_ENV" ]; then
  CONFIG_FILE="$HOMELAB_ENV"
elif [ -f "$LEGACY_CONFIG" ]; then
  echo "Warning: reading credentials from $LEGACY_CONFIG (legacy, repo-local) -- move them to $HOMELAB_ENV once this runs on the Linux server."
  CONFIG_FILE="$LEGACY_CONFIG"
else
  echo "Error: no config found."
  echo "On the server: create $HOMELAB_ENV (see .env.example)."
  echo "On the workstation: copy deploy.config.template to deploy.config and fill in your credentials."
  exit 1
fi

# shellcheck source=deploy.config.template
source "$CONFIG_FILE"

for key in FTP_HOST FTP_USER FTP_PASS FTP_REMOTE_PATH SITE_PASSWORD; do
  if [ -z "${!key:-}" ]; then
    echo "Error: $CONFIG_FILE is missing key: $key"
    exit 1
  fi
done
if [ "$SITE_PASSWORD" = "change-me" ]; then
  echo "Error: $CONFIG_FILE's SITE_PASSWORD is still the template placeholder -- set a real passphrase."
  exit 1
fi

if [ ! -f "$LOCAL_FILE" ]; then
  echo "Error: public/index.html not found. Run 'python app.py' first."
  exit 1
fi

# ── Auth gate ────────────────────────────────────────────────────────────────
# The plaintext SITE_PASSWORD never leaves this process -- only a salted SHA-256
# hash is written to auth_secret.php (generated, gitignored), checked with
# hash_equals() by deploy_auth/login.php for a timing-safe comparison. Salt and
# cookie secret persist across deploys in .auth_state (generated, gitignored) so
# re-deploying doesn't invalidate every saved login; only a real SITE_PASSWORD
# change does that (deliberately -- see deploy_auth/_auth_gate.php).
mkdir -p "$AUTH_DIR"
if [ -f "$AUTH_STATE_FILE" ]; then
  # shellcheck source=/dev/null
  source "$AUTH_STATE_FILE"
else
  AUTH_SALT="$(openssl rand -hex 16)"
  AUTH_COOKIE_SECRET="$(openssl rand -hex 32)"
  printf 'AUTH_SALT=%s\nAUTH_COOKIE_SECRET=%s\n' "$AUTH_SALT" "$AUTH_COOKIE_SECRET" > "$AUTH_STATE_FILE"
fi

# macOS ships `shasum`, not GNU coreutils' `sha256sum` -- try the Linux name first.
if command -v sha256sum >/dev/null 2>&1; then
  PW_HASH="$(printf '%s%s' "$AUTH_SALT" "$SITE_PASSWORD" | sha256sum | cut -d' ' -f1)"
else
  PW_HASH="$(printf '%s%s' "$AUTH_SALT" "$SITE_PASSWORD" | shasum -a 256 | cut -d' ' -f1)"
fi

cat > "$AUTH_SECRET_PHP" <<EOF
<?php
// Generated by deploy.sh from $CONFIG_FILE's SITE_PASSWORD -- do not edit,
// do not commit. Re-run deploy.sh after changing SITE_PASSWORD to update it.
define('SITE_PASSWORD_SALT', '$AUTH_SALT');
define('SITE_PASSWORD_HASH', '$PW_HASH');
define('AUTH_COOKIE_NAME', 'hhc_auth');
define('AUTH_COOKIE_SECRET', '$AUTH_COOKIE_SECRET');
define('AUTH_COOKIE_SECONDS', $AUTH_COOKIE_SECONDS);
EOF

# Pages deploy as .php, never .html -- specifically so the gate below runs
# before any content is sent. Prepending it to an .html file that a plain
# webserver just streams back would be decorative, not enforced.
GATED_PAGE="$(mktemp)"
trap 'rm -f "$GATED_PAGE"' EXIT
{ printf "<?php require __DIR__ . '/_auth_gate.php'; ?>\n"; cat "$LOCAL_FILE"; } > "$GATED_PAGE"

echo "Deploying to ftp://$FTP_HOST$FTP_REMOTE_PATH/ ..."

upload() {
  local src="$1" name="$2"
  curl --silent --show-error \
    --ftp-create-dirs \
    -T "$src" \
    "ftp://$FTP_HOST$FTP_REMOTE_PATH/$name" \
    --user "$FTP_USER:$FTP_PASS"
}

upload "$GATED_PAGE" "index.php"
upload "$AUTH_DIR/_auth_gate.php" "_auth_gate.php"
upload "$AUTH_SECRET_PHP" "auth_secret.php"
upload "$AUTH_DIR/login.php" "login.php"
upload "$AUTH_DIR/robots.txt" "robots.txt"

echo "Done."
