$ConfigFile = "$PSScriptRoot\deploy.config"
$LocalFile  = "$PSScriptRoot\public\index.html"
$AuthDir    = "$PSScriptRoot\deploy_auth"
$AuthStateFile  = "$AuthDir\.auth_state"
$AuthSecretFile = "$AuthDir\auth_secret.php"
$AuthCookieSeconds = 30 * 24 * 60 * 60

if (-not (Test-Path $ConfigFile)) {
    Write-Error "deploy.config not found. Copy deploy.config.template to deploy.config and fill in your credentials."
    exit 1
}

if (-not (Test-Path $LocalFile)) {
    Write-Error "public\index.html not found. Run 'python app.py' first."
    exit 1
}

# Parse key=value config file
$config = @{}
Get-Content $ConfigFile | ForEach-Object {
    if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
        $config[$matches[1].Trim()] = $matches[2].Trim()
    }
}

foreach ($key in @('FTP_HOST', 'FTP_USER', 'FTP_PASS', 'FTP_REMOTE_PATH', 'SITE_PASSWORD')) {
    if (-not $config.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($config[$key])) {
        Write-Error "$ConfigFile is missing key: $key"
        exit 1
    }
}
if ($config['SITE_PASSWORD'] -eq 'change-me') {
    Write-Error "$ConfigFile's SITE_PASSWORD is still the template placeholder -- set a real passphrase."
    exit 1
}

# ── Auth gate ────────────────────────────────────────────────────────────────
# Same mechanism as deploy.sh (see there for the full explanation): the
# plaintext SITE_PASSWORD never leaves this process, only a salted SHA-256
# hash is written to auth_secret.php. Salt and cookie secret persist across
# deploys in .auth_state so re-deploying doesn't invalidate saved logins.
New-Item -ItemType Directory -Force -Path $AuthDir | Out-Null

function New-RandomHex([int]$Bytes) {
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buf)
    -join ($buf | ForEach-Object { $_.ToString('x2') })
}

function Get-Sha256Hex([string]$Text) {
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    $bytes = $sha256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Text))
    -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

if (Test-Path $AuthStateFile) {
    $authState = @{}
    Get-Content $AuthStateFile | ForEach-Object {
        if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
            $authState[$matches[1].Trim()] = $matches[2].Trim()
        }
    }
    $authSalt = $authState['AUTH_SALT']
    $authCookieSecret = $authState['AUTH_COOKIE_SECRET']
} else {
    $authSalt = New-RandomHex 16
    $authCookieSecret = New-RandomHex 32
    "AUTH_SALT=$authSalt`nAUTH_COOKIE_SECRET=$authCookieSecret`n" | Set-Content -NoNewline $AuthStateFile
}

$pwHash = Get-Sha256Hex "$authSalt$($config['SITE_PASSWORD'])"

@"
<?php
// Generated by deploy.ps1 from $ConfigFile's SITE_PASSWORD -- do not edit,
// do not commit. Re-run deploy.ps1 after changing SITE_PASSWORD to update it.
define('SITE_PASSWORD_SALT', '$authSalt');
define('SITE_PASSWORD_HASH', '$pwHash');
define('AUTH_COOKIE_NAME', 'hhc_auth');
define('AUTH_COOKIE_SECRET', '$authCookieSecret');
define('AUTH_COOKIE_SECONDS', $AuthCookieSeconds);
"@ | Set-Content -NoNewline $AuthSecretFile

# Pages deploy as .php, never .html -- so the gate runs before any content is sent.
$gatedPage = New-TemporaryFile
"<?php require __DIR__ . '/_auth_gate.php'; ?>`n" + (Get-Content $LocalFile -Raw) | Set-Content -NoNewline $gatedPage

$remoteBase = "ftp://$($config['FTP_HOST'])$($config['FTP_REMOTE_PATH'])"
Write-Host "Deploying to $remoteBase/ ..."

function Send-File([string]$Src, [string]$Name) {
    curl.exe --silent --show-error `
        --ftp-create-dirs `
        -T $Src `
        "$remoteBase/$Name" `
        --user "$($config['FTP_USER']):$($config['FTP_PASS'])"
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Deployment failed uploading $Name."
        Remove-Item $gatedPage -ErrorAction SilentlyContinue
        exit $LASTEXITCODE
    }
}

Send-File $gatedPage "index.php"
Send-File "$AuthDir\_auth_gate.php" "_auth_gate.php"
Send-File $AuthSecretFile "auth_secret.php"
Send-File "$AuthDir\login.php" "login.php"
Send-File "$AuthDir\robots.txt" "robots.txt"

Remove-Item $gatedPage -ErrorAction SilentlyContinue
Write-Host "Done."
